config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  get 'pages/course'

  get 'pages/register'

  get 'pages/contact'

  get 'pages/login'

  root 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def course
  end

  def register
  end

  def contact
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def cp(path)
  "current" if request.url.include?(path)
end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<div class="row">
			<div class="col-md-4" id="copyright">
				<span>Copyright © Galaxy Technical College 2016</span>
			</div>
			<div class="col-md-4">
				<ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#" class="icoGoogle" title="Google +"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
        </ul>	
			</div>
			<div class="col-md-4">
				<ul class="list-inline quick-links">
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Terms of Use</a></li>
				</ul>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top scrolled" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Galaxy Technical College</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="collapse navbar-collapse" id=".navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <!-- issue `rake routes` command in terminal to get the routes info -->
                            <li class="hvr-pop"><%= link_to "Home", root_path %></li>
                            <li class="hvr-pop"><%= link_to "About", pages_about_path %></li>
                            <li class="hvr-pop"><%= link_to "Course", pages_course_path %></li>
                            <li class="hvr-pop"><%= link_to "Contact", pages_contact_path %></li>
                            <li class="hvr-pop"><%= link_to "Register", pages_register_path %></li>
                            <li class="hvr-pop"><%= link_to "Login", pages_login_path %></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Brand and toggle get grouped for better mobile display -->
            
            <!-- Collect the nav links, forms, and other content for toggling -->
       
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | GTC</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
	<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/navbar' %>
	<div class="container-pages">
			<%= yield %>
	<%= render 'layouts/footer' %>
	</div>

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>

<section id="about">
	<div class="container">
		<div class="row">
			<div class="col-md-8">
				<h1>Who We Are</h1>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam officia ad ullam adipisci commodi ratione iure nobis. Ab aperiam voluptatibus, dolore id, nesciunt laudantium incidunt molestias laboriosam distinctio ipsum, recusandae! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque dolore impedit, pariatur modi error natus voluptates? Debitis, consectetur nulla cum. Maxime facilis fugiat nisi delectus possimus quidem, molestiae quasi eius.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id architecto molestias explicabo porro, officia cum repellendus, alias quos, temporibus quas assumenda minima, iure illum cupiditate inventore dolore aspernatur voluptatum nemo.</p>
			</div>
			<div class="col-md-4">
				<%= image_tag "about_bg.png", :id => "students_bg" %>
			</div>
		</div>
	</div>
</section>

<section id="about_video">
	<div class="container">
		<div class="row">
			<div class="col-md-6">
				<iframe id="college_video" width="560" height="315" src="https://www.youtube.com/embed/8SLYI6n21aE" frameborder="0" allowfullscreen></iframe>
			</div>
				<div class="col-md-6">
					<h2>Checkout What One of Our Students Say!</h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est fugit fugiat nostrum, doloremque expedita quam suscipit recusandae numquam odio accusantium quisquam non, odit ullam quidem doloribus repudiandae quaerat voluptates maxime.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi voluptas debitis, placeat recusandae illum fuga at accusamus. Neque debitis a repellendus numquam, ad exercitationem fuga necessitatibus facilis aut veniam.</p>
				</div>
		</div>
	</div>
</section>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>

<!--Contact-->
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">
                    Contact us <small>Feel free to contact us</small></h1>
            </div>
        </div>
    </div>
</div>
<div id="contact-form" class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                                Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="service">General Customer Service</option>
                                <option value="suggestions">Suggestions</option>
                                <option value="product">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span> Come Visit Us!</legend>
            <address>
                <strong>Galaxy Technical College</strong><br>
                510/451, Pitt Street<br>
                Sydney, NSW 2000<br>
                <abbr title="Phone">
                    P:</abbr>
                (123) 456-7890
            </address>
            <address>
                <strong>email</strong><br>
                <a href="mailto:#">info@galaxytech.com.au</a>
            </address>
            </form>
        </div>
    </div>
</div> <!-- End Contact Form -->

app/views/pages/course.html.erb
<% provide(:title, "Course") %>

<section class="content">
	<div class="course_header">
		<h1>Our Courses</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
	</div>
	
	<div class="course_list">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4">
					<h2>Diploma Courses</h2>
					<ul>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "music.jpg" %>
									</figure>
									<h3>
											<strong>Music</strong> Diploma
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "arts.jpg" %>
									</figure>
									<h3>
											<strong>Arts</strong> Diploma
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "litterature.jpg" %>
									</figure>
									<h3>
											<strong>Litterature</strong> Diploma
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "science.jpg" %>
									</figure>
									<h3>
											<strong>Science</strong> Diploma
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "math.jpg" %>
									</figure>
									<h3>
											<strong>Mathematics</strong> Diploma
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									View all diploma courses
								</a>
							</div>
						</li>
					</ul>
				</div>
				<div class="col-md-4 col-sm-4">
					<h2>Graduate Courses</h2>
					<ul>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "graduate_5.jpg" %>
									</figure>
									<h3>
											<strong>Architecture</strong> Graduate
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "graduate_4.jpg" %>
									</figure>
									<h3>
											<strong>Economics</strong> Graduate
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "graduate_3.jpg" %>
									</figure>
									<h3>
											<strong>Psychology</strong> Graduate
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "graduate_2.jpg" %>
									</figure>
									<h3>
											<strong>Biology</strong> Graduate
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "graduate_1.jpg" %>
									</figure>
									<h3>
											<strong>Engineering</strong> Graduate
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									View all graduate courses
								</a>
							</div>
						</li>
					</ul>
				</div>
				<div class="col-md-4 col-sm-4">
					<h2>Master Courses</h2>
					<ul>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "master_3.jpg" %>
									</figure>
									<h3>
											<strong>Sculpture</strong> Master
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "master_2.jpg" %>
									</figure>
									<h3>
											<strong>Digital media</strong> Master
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									<figure>
										<%= image_tag "master_1.jpg" %>
									</figure>
									<h3>
											<strong>Information technology</strong> Master
									</h3>
									<small>Start 28 Jan, 2016</small>
								</a>
							</div>
						</li>
						<li class="hvr-fade">
							<div>
								<a href="#">
									View all master courses
								</a>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>

<!-- Header -->
<section class="block">
	<div id="myCarousel" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class=""></li>
		<li data-target="#myCarousel" data-slide-to="1" class=""></li>
		<li data-target="#myCarousel" data-slide-to="2" class="active"></li>
	</ol>
	<div class="carousel-inner">
		<div class="item">
			<%= image_tag "slides/slide_1.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>GTC Excellence in Teaching</h1>
					<p>Guiding you all throughout your way to success!</p>
					<p><%= link_to "Register Today", pages_register_path, class: "btn btn-lg btn-primary" %></p>
				</div>
			</div>
		</div>
		<div class="item">
			<%= image_tag "slides/slide_2.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Competent Teachers</h1>
					<p>Qualified instructors that provides knowledge and skills.</p>
					<p><%= link_to "Learn More", pages_about_path, class: "btn btn-lg btn-primary" %></p>
				</div>
			</div>
		</div>
		<div class="item active">
			<%= image_tag "slides/slide_3.jpg" %>
			<div class="container">
				<div class="carousel-caption">
					<h1>Great Students Community</h1>
					<p>A friendly environment that welcomes you.</p>
					<p><%= link_to "Contact Us", pages_contact_path, class: "btn btn-lg btn-primary" %></p>
				</div>
			</div>
		</div>
	</div> <!-- End Header -->



	<a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
	<a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
</section>

<!-- Home Feature 1 -->
<div class="container_gray_bg" id="home_feature_1">
	<div class="container">
		<div class="row">
			<div class="col-md-4" id="columnid1">
				<div class="home_feat_1_box">
					<%= link_to image_tag("home_feat_1_1.jpg", :class => "hvr-float" + " " + "feat_box"), pages_contact_path %>
						<div class="short_info">
							<h3>PLAN A VISIT</h3>
						</div>
				</div>
			</div>
			<div class="col-md-4" id="columnid2">
				<div class="home_feat_1_box">
					<%= link_to image_tag("home_feat_1_2.jpg", :class => "hvr-float" + " " + "feat_box"), pages_course_path %>
						<div class="short_info">
							<h3>STUDY PROGRAMS</h3>
						</div>
				</div>
			</div>
			<div class="col-md-4" id="columnid3">
				<div class="home_feat_1_box">
					<%= link_to image_tag("home_feat_1_3.jpg", :class => "hvr-float" + " " + "feat_box"), pages_register_path %>
						<div class="short_info">
							<h3>ADMISSIONS</h3>
						</div>
				</div>
			</div>
		</div>
	</div> 
</div><!-- End Home Feature -->

<!-- Home Feature 2 -->
<div class="container margin100">
	<div class="main_title">
		<h2 class="text-center">Why Enrol at GTC?</h2>
		<p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis alias distinctio temporibus hic quos saepe facilis quo voluptates deserunt magnam velit, provident exercitationem laborum neque! Temporibus, commodi quaerat fugit totam?</p>
	</div>

		<div class="row">
			<div class="col-md-6" id="columnid4">
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-road"></i>
					<h3>Road to Success</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-ok"></i>
					<h3>Advanced Practice</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-star"></i>
					<h3>Learning Best Practice</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
			</div>
			<div class="col-md-6" id="columnid5">
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-book"></i>
					<h3>Resources</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-search"></i>
					<h3>Research</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
				<div class="box_feat_home">
					<i class="glyphicon glyphicon-usd"></i>
					<h3>Work and Study</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Odit neque, voluptatum distinctio vero quibusdam, quas accusamus cumque, deleniti ex quo quasi velit quaerat. Similique hic, laborum illo vero voluptatibus eius?</p>
				</div>
			</div>
		</div>
</div> <!--End Home Feat 2 -->

<!--Contact-->
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">
                    Contact us <small>Feel free to contact us</small></h1>
            </div>
        </div>
    </div>
</div>
<div id="contact-form" class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                                Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="service">General Customer Service</option>
                                <option value="suggestions">Suggestions</option>
                                <option value="product">Other</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <form>
            <legend><span class="glyphicon glyphicon-globe"></span> Come Visit Us!</legend>
            <address>
                <strong>Galaxy Technical College</strong><br>
                510/451, Pitt Street<br>
                Sydney, NSW 2000<br>
                <abbr title="Phone">
                    P:</abbr>
                (123) 456-7890
            </address>
            <address>
                <strong>email</strong><br>
                <a href="mailto:#">info@galaxytech.com.au</a>
            </address>
            </form>
        </div>
    </div>
</div> <!-- End Contact Form -->

app/views/pages/login.html.erb
<% provide(:title, "Login") %>

<div class="container-fluid" id="login">
	<form class="form-signin">
		<h2 class="form-signin-heading">Please sign in</h2>
		<label for="inputEmail" class="sr-only"></label>
		<input type="email" id="inputEmail" class="form-control" placeholder="Email address" required data-validation-required-message="please enter a valid email address" autofocus> <br>
		<label for="inputPassword" class="sr-only">Password</label>
		<input type="password" id="inputPassword" class="form-control" placeholder="Password" required data-validation-required-message="please enter your password">

		<div class="checkbox">
			<label>
				<input type="checkbox" value="remember-me">Rember me
			</label>
		</div>

		<button class="btn btn-primary btn-lg btn-block" type="submit">Sign-in</button>
	</form>
</div>

app/views/pages/register.html.erb
<% provide(:title, "Register") %>

 <div  class="form">
    		<form id="contactform"> 
    			<p class="contact"><label for="name">Name</label></p> 
    			<input id="name" name="name" placeholder="First and last name" required="" tabindex="1" type="text"> 
    			 
    			<p class="contact"><label for="email">Email</label></p> 
    			<input id="email" name="email" placeholder="example@domain.com" required="" type="email"> 
                
                <p class="contact"><label for="username">Create a username</label></p> 
    			<input id="username" name="username" placeholder="username" required="" tabindex="2" type="text"> 
    			 
                <p class="contact"><label for="password">Create a password</label></p> 
    			<input type="password" id="password" name="password" required=""> 
                <p class="contact"><label for="repassword">Confirm your password</label></p> 
    			<input type="password" id="repassword" name="repassword" required=""> 
        
               <fieldset>
                 <label>Select a course</label> <br>
                  <label class="course_menu"> 
                  <select class="selectpicker" name="course_select">
                  <option value="">Course</option>
                  <option value="01">Music Diploma</option>
                  <option value="02">Arts Diploma</option>
                  <option value="03" >Litterature Diploma</option>
                  <option value="04">Science Diploma</option>
                  <option value="05">Mathematics Diploma</option>
                  <option value="06">Architecture Graduate</option>
                  <option value="07">Economics Graduate</option>
                  <option value="08">Psychology Graduate</option>
                  <option value="09">Biology Graduate</option>
                  <option value="10">Engineering Graduate</option>
                  <option value="11">Sculpture Master</option>
                  <option value="12" >Digital Media Master</option>
                  <option value="13" >Information Technology Master</option>
                  </label>
                 </select>    
              </fieldset> <br>
  
            <select class="selectpicker" name="gender">
            <option value="select">Gender</option>
            <option value="m">Male</option>
            <option value="f">Female</option>
            <option value="others">Other</option>
            </select><br><br>
            
            <p class="contact"><label for="phone">Mobile phone</label></p> 
            <input id="phone" name="phone" placeholder="phone number" required="" type="text"> <br>
            <input class="buttom" name="submit" id="submit" tabindex="5" value="Register" type="submit"> 	 
   </form> 
</div>   